.phony: clean

all: h_p

# a_p: A_problem.cpp
# 	g++  A_problem.cpp -o bin/a_p

# b_p: B_problem.cpp
# 	g++  B_problem.cpp -o bin/b_p

# c_p: C_problem.cpp
# 	g++  C_problem.cpp -o bin/c_p

# d_p: D_problem.cpp
# 	g++  D_problem.cpp -o bin/d_p

# e_p: E_problem.cpp
# 	g++  E_problem.cpp -o bin/e_p

# f_p: F_problem.cpp
# 	g++  F_problem.cpp -o bin/f_p

# g_p: G_problem.cpp
# 	g++  G_problem.cpp -o bin/g_p

h_p: H_problem.cpp
	g++  H_problem.cpp -o bin/h_p